//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholar.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class courseTB
    {
        public int courseID { get; set; }
        public string courseName { get; set; }
        public string courseDetails { get; set; }
        public Nullable<int> userID { get; set; }
        public int instructorID { get; set; }
        public string courseImage { get; set; }
        public string courseStatus { get; set; }
        public string courseTopic { get; set; }
        public string userStatus { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual instructorTB instructorTB { get; set; }
        public virtual userTB userTB { get; set; }
    }
}
