//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTB()
        {
            this.courseTBs = new HashSet<courseTB>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string userMail { get; set; }
        public string Password { get; set; }
        public string userImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courseTB> courseTBs { get; set; }
    }
}
